"use client";
import { useEffect, useState } from "react";
import { createClient } from "@supabase/supabase-js";

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL || "https://mgsbkmyrxrgzbegqipsg.supabase.co",
  process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY || "sb_publishable_AxpRo2RQETwNljCzS3kX7A_UdAeCvnW"
);
const profileImageUrl = (value: string | null | undefined) => { if (!value) return ""; if (/^https?:\/\//i.test(value)) return value; const { data } = supabase.storage.from("vtk-artist-profiles").getPublicUrl(value.replace(/^\/+/, "")); return data.publicUrl; };

const artists = [
  { name: "Voito Taikuma", handle: "@voitotaikuma", genre: "AI Rock · Alternative", initials: "VT", tone: "from-red-600 to-orange-500", followers: "1.2K", bio: "Independent VTK artist building original music.", avatarUrl: "", youtubeUrl: "", spotifyUrl: "", sunoUrl: "" },
  { name: "Bulldog TMC", handle: "@bulldogtmc", genre: "Hardrock · Metal", initials: "BT", tone: "from-zinc-700 to-red-900", followers: "486", bio: "Heavy music, direct energy and uncompromising songs.", avatarUrl: "", youtubeUrl: "", spotifyUrl: "", sunoUrl: "" },
  { name: "Seelenwelt Musik", handle: "@seelenwelt", genre: "Ambient · Healing", initials: "SW", tone: "from-indigo-700 to-cyan-700", followers: "219", bio: "Atmospheric sounds for quiet moments.", avatarUrl: "", youtubeUrl: "", spotifyUrl: "", sunoUrl: "" },
];
const posts = [
  { artist: "Voito Taikuma", handle: "@voitotaikuma", initials: "VT", time: "vor 2 Stunden", title: "The Notorious R", text: "Ein neuer Rockabilly-Trip mit rollendem R, rauem Groove und einer großen Portion Riverboat-Atmosphäre.", tags: ["Rockabilly", "New release"], tone: "from-red-700 to-amber-600" },
  { artist: "Bulldog TMC", handle: "@bulldogtmc", initials: "BT", time: "gestern", title: "The Ground Has Teeth", text: "Deathcore trifft industrielle Spannung: schwer, direkt und ohne unnötigen Glanz.", tags: ["Deathcore", "Heavy music"], tone: "from-neutral-800 to-red-950" },
];

const copy = (language: "EN" | "DE") => language === "DE" ? { community: "COMMUNITY", account: "KONTO", feed: "Feed", artists: "Künstler", songs: "Songs", releases: "Veröffentlichungen", profile: "Mein Profil", admin: "Admin", help: "Hilfe & FAQ", search: "Künstler, Songs, Veröffentlichungen suchen...", songStudio: "Song Studio öffnen", releaseStudio: "Release Studio öffnen" } : { community: "COMMUNITY", account: "ACCOUNT", feed: "Feed", artists: "Artists", songs: "Songs", releases: "Releases", profile: "My profile", admin: "Admin", help: "Help & FAQ", search: "Search artists, songs, releases...", songStudio: "Open Song Studio", releaseStudio: "Open Release Studio" };

function AdminProfiles({ profiles, onDelete, onEdit, onCreate }: { profiles: Array<{ user_id: string; display_name: string | null; nickname: string | null; avatar_url: string | null }>; onDelete: (id: string) => void; onEdit: (id: string) => void; onCreate: () => void }) {
  const [openMenu, setOpenMenu] = useState<string | null>(null);
  const [query, setQuery] = useState("");
  const filtered = profiles.filter((profile) => `${profile.display_name || ""} ${profile.nickname || ""} ${profile.user_id}`.toLowerCase().includes(query.trim().toLowerCase()));
  return <section className="admin-page"><div className="admin-page-head"><div><p className="eyebrow">ADMIN</p><h1>Artist profiles</h1><p>Alle Profile verwalten, bearbeiten oder löschen.</p></div><button type="button" className="primary" onClick={onCreate}>Neues Profil</button></div><input className="admin-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Profile suchen …" aria-label="Profile suchen" /><div className="admin-profile-count">{filtered.length} von {profiles.length} Profilen</div><div className="admin-profile-table">{filtered.length ? filtered.map((profile) => <div className="admin-profile-row" key={profile.user_id}><span className="admin-profile-avatar">{profile.avatar_url ? "●" : "VTK"}</span><div><strong>{profile.display_name || profile.nickname || profile.user_id}</strong><small>{profile.nickname || profile.user_id}</small></div><div className="admin-menu-wrap"><button type="button" className="admin-menu-button" aria-label="Profilaktionen" onClick={() => setOpenMenu(openMenu === profile.user_id ? null : profile.user_id)}>⋯</button>{openMenu === profile.user_id && <div className="admin-menu"><button type="button" onClick={() => onEdit(profile.user_id)}>Bearbeiten</button><button type="button" className="danger" onClick={() => onDelete(profile.user_id)}>Löschen</button></div>}</div></div>) : <p className="admin-empty">Keine passenden Profile gefunden.</p>}</div></section>;
}

export default function Home() {
  const [active, setActive] = useState("Feed");
  const [language, setLanguage] = useState<"EN" | "DE">("EN");
  const text = copy(language);
  const [selectedArtist, setSelectedArtist] = useState<(typeof artists)[number] | null>(null);
  const [liveArtists, setLiveArtists] = useState<typeof artists>([]);
  const goToSection = (item: string, target?: string) => { setActive(item); setAdminOpen(false); setSelectedArtist(null); setTimeout(() => { const node = target ? document.getElementById(target) : item === "My profile" ? document.querySelector(".profile-card") : document.querySelector(".artist-heading"); node?.scrollIntoView({ behavior: "smooth", block: "start" }); }, 0); };
  const [loginOpen, setLoginOpen] = useState(false);
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  const [authMessage, setAuthMessage] = useState("");
  const [userEmail, setUserEmail] = useState("");
  const [artistName, setArtistName] = useState("");
  const [nickname, setNickname] = useState("");
  const [bio, setBio] = useState("");
  const [youtubeUrl, setYoutubeUrl] = useState("");
  const [spotifyUrl, setSpotifyUrl] = useState("");
  const [sunoUrl, setSunoUrl] = useState("");
  const [profileMessage, setProfileMessage] = useState("");
  const [profileImage, setProfileImage] = useState("");
  const isAdmin = userEmail.toLowerCase() === "jobst67@gmail.com";
  const [adminProfiles, setAdminProfiles] = useState<Array<{user_id:string;display_name:string|null;nickname:string|null;avatar_url:string|null}>>([]);
  const [adminOpen, setAdminOpen] = useState(false);
  const displayArtists = liveArtists.length ? liveArtists : artists;
  useEffect(() => { supabase.auth.getSession().then(async ({ data }) => { const user = data.session?.user; const metadata = user?.user_metadata || {}; setUserEmail(user?.email || ""); setArtistName(metadata.artist_name || metadata.full_name || ""); setNickname(metadata.nickname || ""); setBio(metadata.artist_bio || ""); setYoutubeUrl(metadata.youtube_url || ""); setSpotifyUrl(metadata.spotify_url || ""); setSunoUrl(metadata.suno_url || ""); setProfileImage(metadata.avatar_url || ""); if (user) { const { data: profile } = await supabase.from("artist_profiles").select("display_name,nickname,bio,avatar_url,youtube_url,spotify_url,suno_url").eq("user_id", user.id).maybeSingle(); if (profile) { setArtistName(profile.display_name || metadata.artist_name || ""); setNickname(profile.nickname || metadata.nickname || ""); setBio(profile.bio || metadata.artist_bio || ""); setYoutubeUrl(profile.youtube_url || metadata.youtube_url || ""); setSpotifyUrl(profile.spotify_url || metadata.spotify_url || ""); setSunoUrl(profile.suno_url || metadata.suno_url || ""); setProfileImage(profile.avatar_url || metadata.avatar_url || ""); } } }); }, []);
  useEffect(() => { supabase.from("artist_profiles").select("display_name,nickname,bio,avatar_url,youtube_url,spotify_url,suno_url").eq("is_public", true).limit(12).then(({ data }) => { if (data?.length) setLiveArtists(data.map((row, index) => ({ name: row.display_name || row.nickname || "VTK Artist", handle: row.nickname || "@vtkartist", genre: "Independent AI artist", initials: String(row.display_name || "VTK").split(/\\s+/).map((part) => part[0]).join("").slice(0, 2).toUpperCase(), tone: ["from-red-600 to-orange-500", "from-zinc-700 to-red-900", "from-indigo-700 to-cyan-700"][index % 3], followers: "New", bio: row.bio || "Independent VTK artist building original music.", avatarUrl: profileImageUrl(row.avatar_url), youtubeUrl: row.youtube_url || "", spotifyUrl: row.spotify_url || "", sunoUrl: row.suno_url || "" }))); }); }, []);
  useEffect(() => { if (isAdmin) supabase.from("artist_profiles").select("user_id,display_name,nickname,avatar_url").order("created_at", { ascending: false }).then(({ data }) => setAdminProfiles(data || [])); }, [isAdmin, profileMessage]);
  useEffect(() => { if (!profileImage || !userEmail) return; supabase.auth.getUser().then(({ data }) => { if (data.user) supabase.from("artist_profiles").update({ avatar_url: profileImage }).eq("user_id", data.user.id); }); }, [profileImage, userEmail]);
  useEffect(() => { if (selectedArtist?.avatarUrl) { const url = profileImageUrl(selectedArtist.avatarUrl); document.querySelectorAll(".public-profile-art, .artist-cover").forEach((node) => { const element = node as HTMLElement; element.style.backgroundImage = `url(${url})`; element.style.backgroundSize = "cover"; element.style.backgroundPosition = "center"; const initials = element.querySelector("span") as HTMLElement | null; if (initials) initials.style.display = "none"; }); } }, [selectedArtist]);
  useEffect(() => { const timer = window.setTimeout(() => { displayArtists.forEach((artist, index) => { if (!artist.avatarUrl) return; const node = document.querySelectorAll(".artist-cover")[index] as HTMLElement | undefined; if (!node) return; node.style.backgroundImage = `url(${profileImageUrl(artist.avatarUrl)})`; node.style.backgroundSize = "cover"; node.style.backgroundPosition = "center"; const initials = node.querySelector("span") as HTMLElement | null; if (initials) initials.style.display = "none"; }); }, 0); return () => window.clearTimeout(timer); }, [displayArtists]);
  const signIn = async () => {
    setAuthMessage("Signing in...");
    const { data, error } = await supabase.auth.signInWithPassword({ email, password });
    if (error) { setAuthMessage(error.message); return; }
    setUserEmail(data.user?.email || email);
    setLoginOpen(false);
    setAuthMessage("");
  };
  const signOut = async () => { await supabase.auth.signOut({ scope: "local" }); setUserEmail(""); setActive("Feed"); };
  const saveProfile = async () => { setProfileMessage("Saving..."); const { data: userData, error: authError } = await supabase.auth.updateUser({ data: { artist_name: artistName.trim(), nickname: nickname.trim(), artist_bio: bio.trim(), youtube_url: youtubeUrl.trim(), spotify_url: spotifyUrl.trim(), suno_url: sunoUrl.trim() } }); if (authError) { setProfileMessage(authError.message); return; } const user = userData.user; const { error } = await supabase.from("artist_profiles").upsert({ user_id: user.id, display_name: artistName.trim(), nickname: nickname.trim(), bio: bio.trim(), avatar_url: profileImage || null, youtube_url: youtubeUrl.trim() || null, spotify_url: spotifyUrl.trim() || null, suno_url: sunoUrl.trim() || null, is_public: true }, { onConflict: "user_id" }); setProfileMessage(error ? error.message : "Profile saved."); };
  const deleteArtistProfile = async (id: string) => { if (!isAdmin || !window.confirm("Delete this artist profile?")) return; const { error } = await supabase.from("artist_profiles").delete().eq("user_id", id); setProfileMessage(error ? error.message : "Profile deleted."); };
  const editArtistProfile = async (id: string) => { const { data } = await supabase.from("artist_profiles").select("display_name,nickname,bio,avatar_url,youtube_url,spotify_url,suno_url").eq("user_id", id).maybeSingle(); if (!data) return; setArtistName(data.display_name || ""); setNickname(data.nickname || ""); setBio(data.bio || ""); setProfileImage(data.avatar_url || ""); setYoutubeUrl(data.youtube_url || ""); setSpotifyUrl(data.spotify_url || ""); setSunoUrl(data.suno_url || ""); setAdminOpen(false); setActive("My profile"); };
  const uploadProfileImage = async (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; setProfileMessage("Uploading image..."); const { data: userData } = await supabase.auth.getUser(); const user = userData.user; if (!user) { setProfileMessage("Please sign in first."); return; } const image = new Image(); const reader = new FileReader(); reader.onload = () => { image.onload = async () => { const size = Math.min(image.naturalWidth, image.naturalHeight); const canvas = document.createElement("canvas"); canvas.width = 640; canvas.height = 640; const context = canvas.getContext("2d"); if (!context) return; context.drawImage(image, (image.naturalWidth - size) / 2, (image.naturalHeight - size) / 2, size, size, 0, 0, 640, 640); canvas.toBlob(async (blob) => { if (!blob) return; const path = `${user.id}/avatar.webp`; const { error: uploadError } = await supabase.storage.from("vtk-artist-profiles").upload(path, blob, { contentType: "image/webp", upsert: true, cacheControl: "3600" }); if (uploadError) { setProfileMessage(uploadError.message); return; } const { data: urlData } = supabase.storage.from("vtk-artist-profiles").getPublicUrl(path); const url = `${urlData.publicUrl}?v=${Date.now()}`; const { error: profileError } = await supabase.auth.updateUser({ data: { avatar_url: url } }); if (profileError) { setProfileMessage(profileError.message); return; } setProfileImage(url); setProfileMessage("Profile image saved."); }, "image/webp", 0.82); }; image.src = String(reader.result); }; reader.readAsDataURL(file); event.target.value = ""; };
  return <div className="artist-app">
    <aside className="artist-sidebar">
      <a className="artist-logo" href="#top"><span>VTK</span><strong>ARTIST</strong></a>
      <nav><p>{language === "DE" ? "COMMUNITY" : "COMMUNITY"}</p>{[["Feed", "latest-feed"], [language === "DE" ? "Künstler" : "Artists", "featured-artists"], [language === "DE" ? "Songs" : "Songs", "latest-feed"], [language === "DE" ? "Releases" : "Releases", "latest-feed"]].map(([item, target]) => <button type="button" key={item} className={active === item ? "active" : ""} onClick={() => goToSection(item, target)}><span>{item === "Feed" ? "◈" : item === (language === "DE" ? "Künstler" : "Artists") ? "◎" : item === "Songs" ? "♫" : "▣"}</span>{item}</button>)}<p className="space">{language === "DE" ? "KONTO" : "ACCOUNT"}</p><button type="button" className={active === "My profile" ? "active" : ""} onClick={() => goToSection("My profile")}><span>◌</span>{language === "DE" ? "Mein Profil" : "My profile"}</button>{isAdmin && <button type="button" className={adminOpen ? "active" : ""} onClick={() => { setAdminOpen(true); setSelectedArtist(null); }}><span>⚙</span>Admin</button>}</nav>
      <div className="sidebar-studios"><p className="space">VTK STUDIOS</p><a className="studio-link" href="https://vtk-song-studio.com" target="_blank" rel="noreferrer"><span>♫</span>{text.songStudio}</a><a className="studio-link" href="https://release.vtk-song-studio.com" target="_blank" rel="noreferrer"><span>▣</span>{text.releaseStudio}</a></div><div className="sidebar-bottom"><button className="help"><span>?</span>{text.help}</button><small>VTK ARTIST · BETA 0.1.0</small></div>
    </aside>
    <main id="top" className="artist-main">
      <header className="artist-topbar"><label className="artist-search"><span>⌕</span><input placeholder={language === "DE" ? "Künstler, Songs, Releases suchen..." : "Search artists, songs, releases..."} /></label><div className="top-actions"><button type="button" className={`language ${language === "EN" ? "active" : ""}`} onClick={() => setLanguage("EN")}>EN</button><button type="button" className={`language ${language === "DE" ? "active" : ""}`} onClick={() => setLanguage("DE")}>DE</button>{userEmail ? <button type="button" className="sign-in" onClick={signOut}>{language === "DE" ? "Abmelden" : "Sign out"}</button> : <button type="button" className="sign-in" onClick={() => setLoginOpen(true)}>{language === "DE" ? "Anmelden" : "Sign in"}</button>}<button type="button" className="avatar" aria-label="Open account" onClick={() => userEmail ? goToSection("My profile") : setLoginOpen(true)}>VTK</button></div></header>
      <section className={`artist-content ${adminOpen ? "admin-mode" : ""}`}>
        {adminOpen && isAdmin && <AdminProfiles profiles={adminProfiles} onDelete={deleteArtistProfile} onEdit={editArtistProfile} onCreate={() => { setAdminOpen(false); goToSection("My profile"); }} />}
        {active === "My profile" && <section className="profile-card"><div><p className="eyebrow">MY ARTIST PROFILE</p><h2>Your public identity</h2><p className="profile-copy">These details can later appear on your artist profile, songs and releases.</p><div className="profile-avatar">{profileImage ? <img src={profileImage} alt="Profile" /> : <span>VTK</span>}</div><label className="upload-label">Choose profile image<input type="file" accept="image/png,image/jpeg,image/webp" onChange={uploadProfileImage} /></label></div><div className="profile-form"><label>Artist name<input value={artistName} onChange={(event) => setArtistName(event.target.value)} placeholder="e.g. Voito Taikuma" /></label><label>Nickname<input value={nickname} onChange={(event) => setNickname(event.target.value)} placeholder="e.g. @voitotaikuma" /></label><label>Bio<textarea value={bio} onChange={(event) => setBio(event.target.value)} placeholder="Tell listeners about your music..." rows={3} /></label><label>YouTube link<input value={youtubeUrl} onChange={(event) => setYoutubeUrl(event.target.value)} placeholder="https://youtube.com/..." /></label><label>Spotify link<input value={spotifyUrl} onChange={(event) => setSpotifyUrl(event.target.value)} placeholder="https://open.spotify.com/..." /></label><label>Suno link<input value={sunoUrl} onChange={(event) => setSunoUrl(event.target.value)} placeholder="https://suno.com/..." /></label><button className="primary" onClick={saveProfile}>Save profile</button>{profileMessage && <small className={/error|failed|please|violates|not found/i.test(profileMessage) ? "error" : "success"}>{profileMessage}</small>}</div></section>}
        <div className="artist-heading"><div><p className="eyebrow">VTK MUSIC COMMUNITY</p><h1>Artists, songs<br /><em>and releases.</em></h1><p className="lead">A focused home for independent AI artists and the music they build across VTK Song Studio and Release Studio.</p></div><div className="heading-actions"><button className="primary">Create artist profile</button><button className="secondary">Explore releases</button></div></div>
        <section className="feature-card"><div className="feature-art"><div className="feature-mark">VTK</div><span>FEATURED RELEASE</span></div><div className="feature-copy"><p className="eyebrow">FEATURED ARTIST · THIS WEEK</p><h2>The Notorious R</h2><p>Riverboats, whiskey labels and a rockabilly voice with a very distinctive R. Discover the latest VTK project by Voito Taikuma.</p><div className="feature-meta"><span>Voito Taikuma</span><span>6 songs</span><span>Rockabilly</span></div><button type="button" className="text-button" onClick={() => setSelectedArtist(artists[0])}>Open artist profile ↗</button></div></section>
        <div className="section-head"><div><p className="eyebrow">DISCOVER</p><h2>Featured artists</h2></div><button className="text-button">View all artists ↗</button></div>
        <div id="featured-artists" className="artist-grid">{displayArtists.map((artist) => <article className="artist-card" key={artist.handle}><div className={`artist-cover bg-gradient-to-br ${artist.tone}`}><span>{artist.initials}</span></div><div className="artist-card-copy"><h3>{artist.name}</h3><p>{artist.handle}</p><small>{artist.genre}</small><div><span>{artist.followers} followers</span><button type="button" onClick={() => setSelectedArtist(artist)}>View profile</button></div></div></article>)}</div>
        {selectedArtist && <section className="public-profile"><button type="button" className="profile-back" onClick={() => setSelectedArtist(null)}>← Back to artists</button><div className="public-profile-head"><div className={`public-profile-art bg-gradient-to-br ${selectedArtist.tone}`}><span>{selectedArtist.initials}</span></div><div><p className="eyebrow">PUBLIC ARTIST PROFILE</p><h2>{selectedArtist.name}</h2><p className="profile-handle">{selectedArtist.handle} · {selectedArtist.genre}</p><p className="public-bio">{selectedArtist.bio}</p><div className="profile-links">{selectedArtist.youtubeUrl && <a href={selectedArtist.youtubeUrl} target="_blank" rel="noreferrer">YouTube ↗</a>}{selectedArtist.spotifyUrl && <a href={selectedArtist.spotifyUrl} target="_blank" rel="noreferrer">Spotify ↗</a>}{selectedArtist.sunoUrl && <a href={selectedArtist.sunoUrl} target="_blank" rel="noreferrer">Suno ↗</a>}</div></div></div><div className="section-head profile-songs"><div><p className="eyebrow">MUSIC</p><h2>Latest songs</h2></div></div><div className="profile-song-list"><div><strong>The Notorious R</strong><span>Rockabilly · 3:42</span><button type="button">▶</button></div><div><strong>New project coming soon</strong><span>Stay tuned for the next release</span><button type="button">♡</button></div></div></section>}
        <div className="section-head feed-head"><div><p className="eyebrow">LATEST FROM THE COMMUNITY</p><h2>New songs and releases</h2></div><div className="feed-tabs"><button className="selected">All</button><button>Songs</button><button>Releases</button></div></div>
        <div id="latest-feed" className="feed">{posts.map((post) => <article className="post-card" key={post.title}><div className={`post-art bg-gradient-to-br ${post.tone}`}><span>{post.initials}</span><button type="button" aria-label="Play">▶</button></div><div className="post-copy"><div className="post-byline"><strong>{post.artist}</strong><span>{post.handle} · {post.time}</span></div><h3>{post.title}</h3><p>{post.text}</p><div className="post-tags">{post.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><div className="post-actions"><button type="button">♡ Like</button><button type="button">◌ Comment</button><button type="button">↗ Share</button></div></div></article>)}</div>
        <section id="login" className="login-card"><div><p className="eyebrow">ONE VTK ACCOUNT</p><h2>Bring your music with you.</h2><p>Use the same account in Song Studio, Release Studio and Artist. Your profile and connected projects stay together.</p></div><button className="primary" onClick={() => setLoginOpen(true)}>Sign in to VTK</button></section>
      </section>
    </main>
    {loginOpen && <div className="modal-backdrop" onClick={() => setLoginOpen(false)}><div className="login-modal" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={() => setLoginOpen(false)}>×</button><p className="eyebrow">ONE VTK ACCOUNT</p><h2>Sign in</h2><p className="modal-copy">Use your existing Song Studio account.</p><input value={email} onChange={(event) => setEmail(event.target.value)} placeholder="Email" type="email" autoComplete="email" /><div className="password-wrap"><input value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Password" type={showPassword ? "text" : "password"} autoComplete="current-password" /><button type="button" className="password-eye" onClick={() => setShowPassword((value) => !value)} aria-label={showPassword ? "Hide password" : "Show password"}>{showPassword ? "◉" : "◌"}</button></div><button className="primary modal-submit" onClick={signIn}>Sign in</button>{authMessage && <p className="auth-message">{authMessage}</p>}</div></div>}
  </div>;
}
